---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yuk.
--- DateTime: 2021/7/12 1:25
---
local _M = {}

--BaseObject = require("Game.Libs.Module.BaseObject")
print("hello word")

return _M