//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SingletonMonoBehaviour_LuaMgrBridgeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SingletonMonoBehaviour<LuaMgrBridge>), typeof(UnityEngine.MonoBehaviour), "SingletonMonoBehaviour_LuaMgrBridge");
		L.RegFunction("CreateInstance", CreateInstance);
		L.RegFunction("ReleaseInstance", ReleaseInstance);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("s_debugDestroy", get_s_debugDestroy, set_s_debugDestroy);
		L.RegVar("instance", get_instance, null);
		L.RegVar("IsExist", get_IsExist, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			SingletonMonoBehaviour<LuaMgrBridge>.CreateInstance();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			SingletonMonoBehaviour<LuaMgrBridge>.ReleaseInstance();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_s_debugDestroy(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, SingletonMonoBehaviour<LuaMgrBridge>.s_debugDestroy);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, SingletonMonoBehaviour<LuaMgrBridge>.instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsExist(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, SingletonMonoBehaviour<LuaMgrBridge>.IsExist);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_s_debugDestroy(IntPtr L)
	{
		try
		{
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			SingletonMonoBehaviour<LuaMgrBridge>.s_debugDestroy = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

